### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by keithort** [spences10/cv#510]
The image "https://pbs.twimg.com/profile_images/1039594009562435584/8xiMh2Wf_400x400.jpg" is missing in the header.

**Comment by spences10** [comment]
Hey @keithort I've only just noticed this issue!

Apologies I missed it!!

Can you tell me if you are still having the same issue?

I know I may have changed my profile image around that time on Twitter so that probably why it's broken.

Let me know if there's anything else you need help with otherwise I'll close this if I don't hear back from you.

**Comment by keithort** [comment]
You got it fixed.
